# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151024185721 on 2015-12-01 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20151201_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='ord',
            name='isbn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book'),
        ),
    ]
