# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151024185721 on 2015-12-01 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_ord_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ord',
            old_name='isbn',
            new_name='book',
        ),
    ]
