# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151024185721 on 2015-12-04 16:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_opinion_usefulness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ord',
            name='qty',
            field=models.CommaSeparatedIntegerField(default=0, max_length=128, validators=[django.core.validators.MinValueValidator(0, b'Order quantity cannot be negative.')]),
        ),
    ]
