# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151024185721 on 2015-12-04 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_auto_20151204_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ord',
            name='book',
        ),
        migrations.AddField(
            model_name='ord',
            name='book',
            field=models.ManyToManyField(to='bookstore.Book'),
        ),
    ]
