# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151024185721 on 2015-12-04 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0014_ord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ord',
            name='book',
        ),
        migrations.RemoveField(
            model_name='ord',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Ord',
        ),
    ]
