# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151024185721 on 2015-12-05 03:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0016_ord'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, b'Order quantity cannot be negative.')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book')),
            ],
        ),
        migrations.RemoveField(
            model_name='ord',
            name='book',
        ),
        migrations.RemoveField(
            model_name='ord',
            name='qty',
        ),
        migrations.AddField(
            model_name='ordbook',
            name='oid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Ord'),
        ),
        migrations.AlterUniqueTogether(
            name='ordbook',
            unique_together=set([('oid', 'book')]),
        ),
    ]
